apiVersion: v1
kind: Pod
metadata:
  name: happylittledotnetpod
  labels:
    name: happylittleapp
spec:
  containers:
  - name: dotnetservice
    image: myaspnetcorefornet5service
    imagePullPolicy: IfNotPresent
    ports :
      - containerPort: 90
    resources:
        limits:
          cpu: 1000m
          memory: 1Gi
        requests:
          cpu: 500m
          memory: 1Gi

