apiVersion: apps/v1
kind: Deployment
metadata:
  name: aspnet-core-secrets-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: aspnet-core-secrets-demo
  template:
    metadata:
      labels:
        app: aspnet-core-secrets-demo
    spec:
      containers:
      - name: aspnet-core-secrets-demo
        image: aspnet-core-secrets:coolest
        ports:
        - containerPort: 5555
        env:
        - name: "ASPNETCORE_ENVIRONMENT"
          value: "Kubernetes"
        volumeMounts:
        - name: secrets
          mountPath: /app/secrets
          readOnly: true
      volumes:
      - name: secrets
        secret:
          secretName: secret-appsettings