apiVersion: v1
kind: Service
metadata:
  name: aspnet-core-secrets-demo-service
spec:
  selector:
    app: aspnet-core-secrets-demo
  ports:
  - protocol: TCP
    port: 5555
    targetPort: 5555
  type: LoadBalancer
